### ISSUE TITLE
Problem with date compare clientside validation

### ISSUE THREAD

**Issue by matias-yii** [EAnushan/yii2-datetime-compare#5]
If you use date with format d/m/Y or d-m-Y the client validation fail because Date function converts these dates wrong. I could add this patch 
 if (options.format) {
                var tempDate = '';
                var tempDateCompare = '';

```
            if (options.format.toLowerCase().indexOf('m') > options.format.toLowerCase().indexOf('d')) {
                if (value.indexOf('/') !== -1) {

                    tempDate = value.split('/');
                    tempDateCompare = compareValue.split('/');
                    value = tempDate[1] + '/' + tempDate[0] + '/' + tempDate[2];
                    compareValue = tempDateCompare[1] + '/' + tempDateCompare[0] + '/' + tempDateCompare[2];
                }
                if (value.indexOf('-') !== -1) {
                    tempDate = value.split('-');
                    tempDateCompare = compareValue.split('-');
                    value = tempDate[1] + '-' + tempDate[0] + '-' + tempDate[2];
                    compareValue = tempDateCompare[1] + '-' + tempDateCompare[0] + '-' + tempDateCompare[2];
                }

            }
        }
```

Other idea is to use moment.js instead.

**Comment by arogachev** [comment]
I was going to create the same issue.

Handling dates in JS is a bit tough. Currently if date is specified like `date('Y-m-d H:i:s')` in validation rule, client validation will always fail, because when it's passed to `new Date()` constructor it will be invalid date. In this case it needs to be `new Date('2015-01-22T10:30:00')`, but there are more different possible combinations. Also different browsers have different behavior related with date processing.

I'd recommend to switch to moment.js or something similar, it will add extra dependency, but will be more reliable. Look for example how it's implemented [here](https://github.com/nepstor/yii2-datetime-compare-validator/blob/master/assets/js/datetime-compare-validator.js).

**Comment by EAnushan** [comment]
Thank you, you're right. I will most likely end up switching to moment.js. It will, as you mentioned, alleviate cross browser nuances as well.

**Comment by EAnushan** [comment]
Please take a look at the above pull request and let me know if it is what you expected. I might end up using https://github.com/kartik-v/php-date-formatter instead of moment.js in the future, so we can re-use the PHP date format option for JavaScript as well.

**Comment by arogachev** [comment]
Personally I wouldn't rely on [this](https://github.com/kartik-v/php-date-formatter).

**Comment by EAnushan** [comment]
I'm curious, do you mind elaborating on why you wouldn't rely on it?

**Comment by matias-yii** [comment]
There is an issue with momemjs library => "Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info." when it try to creates the objects.
