### ISSUE TITLE
Issue with momentjs

### ISSUE THREAD

**Issue by matias-yii** [EAnushan/yii2-datetime-compare#7]
There is an issue with momemjs library => "Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to moment/moment#1407 for more info." when it tries to create the objects.

**Comment by EAnushan** [comment]
Seems like this is expected behavior. You either need to pass a valid iso date, or you need to explicitly provide the `jsFormat`. If you are using a non-iso format, moment will not be able to guess your format correctly and will fallback to using regular javascript Date (which may not produce the results you were looking for, thus the deprecation warning).
