### ISSUE TITLE
Wrong use of $.inArray

### ISSUE THREAD

**Issue by aliechti** [EAnushan/yii2-datetime-compare#8]
The JQuery `$.inArray` method is only for searching trough arrays and not for object keys.

It should be more like this:

``` javascript
var dateValue = 'format' in options ? moment(value, options['format']).unix() : moment(new Date(value)).unix();
var dateCompareValue = 'format' in options ? moment(compareValue, options['format']).unix() : moment(new Date(compareValue)).unix();
```

I've also added `new Date()` because of the MomentJS deprecated warning: https://github.com/moment/moment/issues/1407

**Comment by EAnushan** [comment]
Thanks for the bug report.

I took a look at yii's built in validator js. It uses the following format:

```
if (options.maxSize && options.maxSize < file.size) {
    messages.push(options.tooBig.replace(/\{file\}/g, file.name));
}
```

I'll switch ours to use the same.

Regarding the use of `new Date()`. I don't think this is a good idea. The reason you're getting a deprecation warning is because moment js no longer supports guessing non-iso date formats, as mentioned in the issue you linked. That means, if you are using a non-standard date format, you should also provide the `options['format']` option, so that moment js knows what format to expect.

**Comment by EAnushan** [comment]
I merged in a fix to access `options` as an object instead of an array. Let me know if this addresses your concerns.
